name: Bug Report
description: File a bug report
title: "Bug"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: "Check out [Supported OD list](https://github.com/ZimCodes/Zeiver/blob/main/OD.md)."
  - type: checkboxes
    id: support_check
    attributes:
      label: OD Support
      description: Is the OD part of the currently supported list?
      options:
        - label: OD
          required: true
  - type: input
    id: summary
    attributes:
      label: Summary
      description: Provide a clear and concise description of the issue.
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Details
      description: Provide a detailed description of the issue as well as how to reproduce it.
    validations:
      required: true
  - type: textarea
    id: sources
    attributes:
      label: Screenshots/Links
      description: If applicable, add screenshots and/or a link to help explain your problem.'
    validations:
      required: false
  - type: textarea
    id: comments
    attributes:
      label: Comments
      description: Any other information you would like to add?
    validations:
      required: false


