name: Feature Request
description: Suggest an idea for this project
title: "New Feature"
labels: [ "enhancement" ]
body:
  - type: input
    id: summary
    attributes:
      label: Summary
      description: Provide a clear and concise description of the issue.
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Details
      description: Provide a detailed description of the issue as well as how to reproduce it.
    validations:
      required: true
  - type: textarea
    id: sources
    attributes:
      label: References
      description: If applicable, add references (such as screenshots, links) to help explain your
      problem.
    validations:
      required: false
  - type: textarea
    id: comments
    attributes:
      label: Comments
      description: Any other information you would like to add?
    validations:
      required: false