[package]
name = "recorder"
version = "0.3.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scraper = {path = "../scraper"}
asset = {path = "../asset"}
tokio = { version = "1.10.1", features = ["fs","io-util"] }
