[package]
name = "cmd_opts"
version = "0.8.5"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "~3.2.10", features = ["derive"]}