[package]
name = "grabber"
version = "0.3.1-1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logger = {path = "../logger"}
rand = ">=0.8.4"
reqwest = "~0.11.4"