name: Build

on:
  push:
    branches:
      - main
      - dev

jobs:
  testing_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update Rust
        run: |
        rustup update
        cargo fix --edition
        cargo check
      - name: Test Cargo
        run: cargo test --workspace
  testing_windows_job:
    runs-on: windows-latest
    steps:
      - uses: actions/@checkoutv2
      - name: Update Rust
        run: |
        rustup update
        cargo fix --edition
        cargo check
      - name: Test Cargo
        run: cargo test --workspace