name: Push Rust

on:
  push:
    branches:
      - main
      - dev

jobs:
  testing_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test Cargo
        run: cargo test --workspace