name: Timed Rust Update

on:
  schedule:
    - cron: '* 12 1,17 * *'

jobs:
  update_rust_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update Rust
        run: rustup update
      - name: Update Dependencies
        run: cargo update
      - name: Push to Repository
        run: |
          git status
          git config --global user.email ${{secrets.EMAIL}}
          git config --global user.name ${{secrets.NAME}}
          git add -A
          git commit -m "update cargo dependencies"
          git push origin main
          git status